@startuml
!include style.iuml
title Digital Dungeons - Diagram ER (Baza danych)
left to right direction

entity "users" as USERS {
  * user_id : INT <<PK>>
  --
  username : VARCHAR
  email : VARCHAR
  password : VARCHAR
  profile_bio : TEXT
  join_date : DATETIME
  last_login : DATETIME
  is_active : BOOLEAN
}

entity "games" as GAMES {
  * game_id : INT <<PK>>
  --
  author_id : INT <<FK>>
  title : VARCHAR
  description : TEXT
  game_content : JSON
  is_published : BOOLEAN
  likes_count : INT
  plays_count : INT
  create_date : DATETIME
  update_date : DATETIME
}

entity "playthroughs" as PLAYTHROUGHS {
  * playthrough_id : INT <<PK>>
  --
  game_id : INT <<FK>>
  user_id : INT <<FK>>
  game_state : JSON
  status : ENUM
  start_date : DATETIME
  last_active : DATETIME
}

entity "likes" as LIKES {
  * like_id : INT <<PK>>
  --
  user_id : INT <<FK>>
  game_id : INT <<FK>>
  date_liked : DATETIME
}

entity "comments" as COMMENTS {
  * comment_id : INT <<PK>>
  --
  game_id : INT <<FK>>
  user_id : INT <<FK>>
  content : TEXT
  date_posted : DATETIME
  is_edited : BOOLEAN
}

USERS ||--o{ GAMES : tworzy
GAMES ||--o{ PLAYTHROUGHS : posiada
USERS ||--o{ PLAYTHROUGHS : prowadzi
GAMES ||--o{ COMMENTS : ma
USERS ||--o{ COMMENTS : dodaje
USERS ||--o{ LIKES : wystawia
GAMES ||--o{ LIKES : otrzymuje
@enduml
